{% set name = "keyrings.alt" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: 8f097ebe9dc8b185106502b8cdb066c926d2180e13b4689fd4771a3eab7d69fb

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61.2
    - setuptools-scm >=3.4.1
    - toml
  run:
    - python
    - jaraco.classes
    - jaraco.context

test:
  source_files:
    - tests
  imports:
    - keyrings.alt
  requires:
    - pip
    - pytest >=6,!= 8.1.*
    - keyring >=20
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate keyring backend implementations for use with the keyring package.
  doc_url: https://github.com/jaraco/keyrings.alt
  dev_url: https://github.com/jaraco/keyrings.alt

extra:
  recipe-maintainers:
    - astaric
