{% set name = "keyrings.alt" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/keyrings.alt-{{ version }}.tar.gz
  sha256: 9d446cb47bbcea90ffa2ecc3e8003acf41573fc201bf44b4bf13bd0e11484828


build:
  number: 0
  script: {{ PYTHON }} -n pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=56
    - setuptools-scm >=3.4.1
    - wheel
  run:
    - python
    - jaraco.classes

test:
  imports:
    - keyrings.alt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate keyring backend implementations for use with the keyring package.
  doc_url: https://github.com/jaraco/keyrings.alt
  dev_url: https://github.com/jaraco/keyrings.alt

extra:
  recipe-maintainers:
    - astaric
