{% set name = "keyrings.alt" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/keyrings.alt/keyrings_alt-5.0.2.tar.gz
  sha256: 8f097ebe9dc8b185106502b8cdb066c926d2180e13b4689fd4771a3eab7d69fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools-scm >=3.4.1
  run:
    - python
    - jaraco.classes
    - jaraco.context

test:
  imports:
    - keyrings.alt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jaraco/keyrings.alt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate keyring backend implementations for use with the keyring package.
  doc_url: https://github.com/jaraco/keyrings.alt
  dev_url: https://github.com/jaraco/keyrings.alt

extra:
  recipe-maintainers:
    - astaric
