travis:
  secure:
    BINSTAR_TOKEN: EZGj9AQ9xnv95ak8Ag0jTOxVxwBL7L0zwSN+9EHWEJm35ShBPQ6lAJ+v62VSvQEfEw0bRprDOatIz+tkjDOvIox9HhmbrEWFFt11CP8SjTvfLPB06K2ET8HUYpIm192Vfnd0gc3JExyRlJ5pVllFKY++ubgTsoNqK9RvI5FJlQAMh+V0b8ZHhRzINf1bAueXVZ/3WJhDWNXUQxTJ7gvtEW6zIWspFbRl2aCCNDhc11jMM1KzUB1yP2yp/+O2yxJnDEMXL/MgAMB1Czt3JlixJwPLqqJ6e7B8Dh5ybWW0kACmpHfd08NNlhqioPVHp1eOxkucO0cj9BTTVEcI7hTQhmCfNh6aUyhKs/TEl2ecZKHt32atANHfm+mK8NWrIS7lEJVIO5euf4Rz++3rdCxxGtBMxy7AKfSov3I6FMurg/ZrulEz4L0Z6YmgFBV5BIlGJ0ZeckHKoPrK0MSUJ76SjzwwAHbEixWZ7l5hNbiWzK4p6oj+L967xWYSoQxxfLFdkchJz/Pu3fl6n5awZeQfEyKuzb63+vuPFsTs/SzG8igZZUoGKxSKNZ1hEJJwMPj3GDqnGmDyMNXZbP4ZMxttdbPJ+p7JEVaYPIVLWJeHvqeHqn4HUVvbl6aMeucyyRNNyVMfINMmSr6+34VVVfRo5L0CK//ctclRnCue7zr0ZX8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
