travis:
  secure:
    BINSTAR_TOKEN: RiUkH44OLqggrmmLsAUXZ3MXpXcJ+Dle+nCdmM3ehqqan+vRtTBrfqUys5aeM+muzJ0c7IKcgl5JHNmwzfjWErw18Znb6QyVxKge9vqdvQFVqG2X++IM8HpMgIYTXcMuycnOKAvRf50dODMIfVdVTcu1Atx7iKRtjwFJ3uLprP/ZDeQ2vji/TF6gMkWqTxOmSx4ZiXLT9nQ5EbJ7CZcPV+HAMSnRlwjcUEMbG87sbhemv4QfXrP1TIOqAoztNAE4KmneZ+u8UUlj7p1xQlaMDbNaPGf81Ux/wpclJo2InrrkMlr0sUx6H4dDHzs6YKj18FeRelzbvWAoErOp4AzRjpH1om4+DHq/wlr3n/f5Iy+hSTBBk4Tq7L71cuaelZSgpIqRdYmObMOkCZTIfMAooszkDf2iaNtuj5LOXXcOmdfDyDyfrGnWcK4VUJJEfObFP845bVudgTiG5n24vj8be/ZS+xRgKwRHpc3pMkecyegYVIH4+QrFBBo/4uoO4B/kKFDOrU0en4vvIGM2xIBVhxs8dOGgTdWDrcfVPGj/Xs4LotrjjewhZ13RAa1/oW009x/a8LA24XBkwRy529WFyRNq92lgn82VUQoVTmFTPQ8gJfypTwfU119WmzyPxygfCiGP2+YNkZY0AAhiZ4dBYQT9wnz1NQYcxczp5IeV/WU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
