travis:
  secure:
    BINSTAR_TOKEN: KH0M/GDYsHhTWRb01VcG6w9TICXyop4hX4YznmgIoNDCOWVCz+8Hj57o8HFoSJHCs939MhCXyBTwhC1mBhVfFLbmKEM3iI+l6ecK+llXVUFV2MKyrPX1ISTfe391yR6j4lfsea8+P81+gbc3MrNsVU1PBv4CiM1nr726lKpYXOIZCieQIP50qkrpLSWhwK9DBi4HH2oNw/MnPkHwrt6hYKAVPQxv1NI4rkB5e2A+xOn8ys9nghAP38F9IPyHTFQD0K1xT3zIJTqnjYzQ/08fXl8OSCNnBkPBIx0QGyNb56h4GvL6SKao8xyNGtTzuFRQfFSjVVb0B/D8i4y5pORRlzHnPVJjC0O04I10HhQPYzQDJzHWeVJuU7u5bUvuWFPDaC9JKYk8HqseDHiz8qjr9lpKrW756i9cd6QyHnJCNjXenXdvMw0q7UYD8whwMroY9bKxf/1eu9n5ETLj45YokFivABWfAbnYx3Wzcfnx8X0vYA561SOqLDUizgTLKu1CsB0m9w1DkN+In2U2H+gBcw1bcgGgLr7fpQo3MDdiJvfXvMKpbAPrsmbYqtYnd+513M+uhjgOggjkorPPyKgkZ3TCgqW7qU2VlHU0J0aSNRQ32LXXPBFTzQW0+tqQmU7wRWTrCi05uLRHu/z/1nrdS7PYrZ3gSfbtn+S1xo2cm80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
